import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const translations = [
    { key: "tabs.collections", locale: "en", value: "Collections", namespace: "AdminDashboard" },
    { key: "tabs.settings", locale: "en", value: "Settings", namespace: "AdminDashboard" },
    { key: "tabs.upload", locale: "en", value: "Upload Documents", namespace: "AdminDashboard" },
    { key: "title", locale: "en", value: "Admin Dashboard", namespace: "AdminDashboard" },
    { key: "tabs.collections", locale: "it", value: "Collezioni", namespace: "AdminDashboard" },
    { key: "tabs.settings", locale: "it", value: "Impostazioni", namespace: "AdminDashboard" },
    { key: "tabs.upload", locale: "it", value: "Carica Documenti", namespace: "AdminDashboard" },
    { key: "title", locale: "it", value: "Pannello di Amministrazione", namespace: "AdminDashboard" },
    { key: "sessionExpired.backToLogin", locale: "en", value: "Back to Login", namespace: "Auth" },
    { key: "sessionExpired.description", locale: "en", value: "Your session has expired. To continue using the application you need to log in again.", namespace: "Auth" },
    { key: "sessionExpired.okButton", locale: "en", value: "OK", namespace: "Auth" },
    { key: "sessionExpired.title", locale: "en", value: "Session Expired", namespace: "Auth" },
    { key: "sessionExpired.backToLogin", locale: "it", value: "Torna al Login", namespace: "Auth" },
    { key: "sessionExpired.description", locale: "it", value: "La tua sessione è scaduta. Per continuare a utilizzare l'applicazione è necessario effettuare nuovamente l'accesso.", namespace: "Auth" },
    { key: "sessionExpired.okButton", locale: "it", value: "OK", namespace: "Auth" },
    { key: "sessionExpired.title", locale: "it", value: "Sessione Scaduta", namespace: "Auth" },
    { key: "brandCode", locale: "en", value: "Brand Code", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.brandCode", locale: "en", value: "Brand Code:", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.contactAdmin", locale: "en", value: "Please contact your administrator to enable access for this brand.", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.description", locale: "en", value: "Your brand is not supported or inactive.", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.notAvailable", locale: "en", value: "Not available", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.title", locale: "en", value: "Brand Not Supported", namespace: "BrandConfiguration" },
    { key: "company", locale: "en", value: "Company", namespace: "BrandConfiguration" },
    { key: "companyDescription", locale: "en", value: "Description", namespace: "BrandConfiguration" },
    { key: "description", locale: "en", value: "Manage API keys and settings for {companyName}", namespace: "BrandConfiguration" },
    { key: "errors.brandValidationFailed", locale: "en", value: "Brand validation failed", namespace: "BrandConfiguration" },
    { key: "errors.failedToLoadSettings", locale: "en", value: "Failed to load settings", namespace: "BrandConfiguration" },
    { key: "errors.failedToUpdateSetting", locale: "en", value: "Failed to update setting", namespace: "BrandConfiguration" },
    { key: "errors.failedToValidate", locale: "en", value: "Failed to validate brand access", namespace: "BrandConfiguration" },
    { key: "errors.noBrandInSession", locale: "en", value: "No brand found in user session", namespace: "BrandConfiguration" },
    { key: "loadingSettings", locale: "en", value: "Loading settings...", namespace: "BrandConfiguration" },
    { key: "securityNote", locale: "en", value: "API keys are encrypted • Flow IDs are stored as plain text", namespace: "BrandConfiguration" },
    { key: "settings.chatFlowId.description", locale: "en", value: "Specify the Langflow chat workflow for {companyName}", namespace: "BrandConfiguration" },
    { key: "settings.chatFlowId.title", locale: "en", value: "Chat Flow ID", namespace: "BrandConfiguration" },
    { key: "settings.embeddingsFlowId.description", locale: "en", value: "Configure data processing workflow for {companyName}", namespace: "BrandConfiguration" },
    { key: "settings.embeddingsFlowId.title", locale: "en", value: "Embeddings Flow ID", namespace: "BrandConfiguration" },
    { key: "settings.langflowApiKey.description", locale: "en", value: "Configure Langflow API access for workflow management", namespace: "BrandConfiguration" },
    { key: "settings.langflowApiKey.title", locale: "en", value: "Langflow API Key", namespace: "BrandConfiguration" },
    { key: "settings.openaiApiKey.description", locale: "en", value: "Configure OpenAI API access for AI-powered features", namespace: "BrandConfiguration" },
    { key: "settings.openaiApiKey.title", locale: "en", value: "OpenAI API Key", namespace: "BrandConfiguration" },
    { key: "title", locale: "en", value: "Brand Configuration", namespace: "BrandConfiguration" },
    { key: "validatingBrand", locale: "en", value: "Validating brand access...", namespace: "BrandConfiguration" },
    { key: "verifiedBrand", locale: "en", value: "Verified Brand", namespace: "BrandConfiguration" },
    { key: "brandCode", locale: "it", value: "Codice Brand", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.brandCode", locale: "it", value: "Codice Brand:", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.contactAdmin", locale: "it", value: "Contatta il tuo amministratore per abilitare l'accesso per questo brand.", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.description", locale: "it", value: "Il tuo brand non è supportato o non è attivo.", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.notAvailable", locale: "it", value: "Non disponibile", namespace: "BrandConfiguration" },
    { key: "brandNotSupported.title", locale: "it", value: "Brand Non Supportato", namespace: "BrandConfiguration" },
    { key: "company", locale: "it", value: "Azienda", namespace: "BrandConfiguration" },
    { key: "companyDescription", locale: "it", value: "Descrizione", namespace: "BrandConfiguration" },
    { key: "description", locale: "it", value: "Gestisci chiavi API e impostazioni per {companyName}", namespace: "BrandConfiguration" },
    { key: "errors.brandValidationFailed", locale: "it", value: "Validazione brand fallita", namespace: "BrandConfiguration" },
    { key: "errors.failedToLoadSettings", locale: "it", value: "Impossibile caricare le impostazioni", namespace: "BrandConfiguration" },
    { key: "errors.failedToUpdateSetting", locale: "it", value: "Impossibile aggiornare l'impostazione", namespace: "BrandConfiguration" },
    { key: "errors.failedToValidate", locale: "it", value: "Impossibile validare l'accesso al brand", namespace: "BrandConfiguration" },
    { key: "errors.noBrandInSession", locale: "it", value: "Nessun brand trovato nella sessione utente", namespace: "BrandConfiguration" },
    { key: "loadingSettings", locale: "it", value: "Caricamento impostazioni...", namespace: "BrandConfiguration" },
    { key: "securityNote", locale: "it", value: "Le chiavi API sono crittografate • Gli ID dei flussi sono memorizzati in chiaro", namespace: "BrandConfiguration" },
    { key: "settings.chatFlowId.description", locale: "it", value: "Specifica il workflow chat Langflow per {companyName}", namespace: "BrandConfiguration" },
    { key: "settings.chatFlowId.title", locale: "it", value: "ID Flusso Chat", namespace: "BrandConfiguration" },
    { key: "settings.embeddingsFlowId.description", locale: "it", value: "Configura il workflow di elaborazione dati per {companyName}", namespace: "BrandConfiguration" },
    { key: "settings.embeddingsFlowId.title", locale: "it", value: "ID Flusso Embeddings", namespace: "BrandConfiguration" },
    { key: "settings.langflowApiKey.description", locale: "it", value: "Configura l'accesso API Langflow per la gestione dei workflow", namespace: "BrandConfiguration" },
    { key: "settings.langflowApiKey.title", locale: "it", value: "Chiave API Langflow", namespace: "BrandConfiguration" },
    { key: "settings.openaiApiKey.description", locale: "it", value: "Configura l'accesso API OpenAI per le funzionalità basate su AI", namespace: "BrandConfiguration" },
    { key: "settings.openaiApiKey.title", locale: "it", value: "Chiave API OpenAI", namespace: "BrandConfiguration" },
    { key: "title", locale: "it", value: "Configurazione Brand", namespace: "BrandConfiguration" },
    { key: "validatingBrand", locale: "it", value: "Validazione accesso brand...", namespace: "BrandConfiguration" },
    { key: "verifiedBrand", locale: "it", value: "Brand Verificato", namespace: "BrandConfiguration" },
    { key: "deleteDialog.allDocumentsIn", locale: "en", value: "all documents in", namespace: "collectionDetails" },
    { key: "description", locale: "en", value: "View and manage your collection information. The settings section allows you to update collection metadata properties.", namespace: "collectionDetails" },
    { key: "error.deleteDocuments", locale: "en", value: "Failed to delete documents", namespace: "collectionDetails" },
    { key: "error.update", locale: "en", value: "Failed to update collection", namespace: "collectionDetails" },
    { key: "settings.addField", locale: "en", value: "Add Field", namespace: "collectionDetails" },
    { key: "settings.attributes", locale: "en", value: "Attributes", namespace: "collectionDetails" },
    { key: "settings.cancel", locale: "en", value: "Cancel", namespace: "collectionDetails" },
    { key: "settings.deleteDocuments", locale: "en", value: "Delete All Documents", namespace: "collectionDetails" },
    { key: "settings.deletingDocuments", locale: "en", value: "Deleting Documents...", namespace: "collectionDetails" },
    { key: "settings.description", locale: "en", value: "Description", namespace: "collectionDetails" },
    { key: "settings.descriptionPlaceholder", locale: "en", value: "Add a description...", namespace: "collectionDetails" },
    { key: "settings.edit", locale: "en", value: "Edit", namespace: "collectionDetails" },
    { key: "settings.inUse", locale: "en", value: "in use", namespace: "collectionDetails" },
    { key: "settings.metadata", locale: "en", value: "Metadata", namespace: "collectionDetails" },
    { key: "settings.name", locale: "en", value: "Collection Name", namespace: "collectionDetails" },
    { key: "settings.save", locale: "en", value: "Save Changes", namespace: "collectionDetails" },
    { key: "settings.selectKey", locale: "en", value: "Select a key", namespace: "collectionDetails" },
    { key: "settings.title", locale: "en", value: "Settings", namespace: "collectionDetails" },
    { key: "settings.valuePlaceholder", locale: "en", value: "Value (max 35 chars)", namespace: "collectionDetails" },
    { key: "stats.documents", locale: "en", value: "Total Documents", namespace: "collectionDetails" },
    { key: "stats.title", locale: "en", value: "Statistics", namespace: "collectionDetails" },
    { key: "title", locale: "en", value: "Collection Details", namespace: "collectionDetails" },
    { key: "deleteDialog.allDocumentsIn", locale: "it", value: "tutti i documenti in", namespace: "collectionDetails" },
    { key: "description", locale: "it", value: "Visualizza e gestisci le informazioni della tua collezione. La sezione impostazioni consente di aggiornare le proprietà dei metadati della collezione.", namespace: "collectionDetails" },
    { key: "error.deleteDocuments", locale: "it", value: "Impossibile eliminare i documenti", namespace: "collectionDetails" },
    { key: "error.update", locale: "it", value: "Impossibile aggiornare la collezione", namespace: "collectionDetails" },
    { key: "settings.addField", locale: "it", value: "Aggiungi Campo", namespace: "collectionDetails" },
    { key: "settings.attributes", locale: "it", value: "Attributi", namespace: "collectionDetails" },
    { key: "settings.cancel", locale: "it", value: "Annulla", namespace: "collectionDetails" },
    { key: "settings.deleteDocuments", locale: "it", value: "Elimina Tutti i Documenti", namespace: "collectionDetails" },
    { key: "settings.deletingDocuments", locale: "it", value: "Eliminazione Documenti...", namespace: "collectionDetails" },
    { key: "settings.description", locale: "it", value: "Descrizione", namespace: "collectionDetails" },
    { key: "settings.descriptionPlaceholder", locale: "it", value: "Aggiungi una descrizione...", namespace: "collectionDetails" },
    { key: "settings.edit", locale: "it", value: "Modifica", namespace: "collectionDetails" },
    { key: "settings.inUse", locale: "it", value: "in uso", namespace: "collectionDetails" },
    { key: "settings.metadata", locale: "it", value: "Metadati", namespace: "collectionDetails" },
    { key: "settings.name", locale: "it", value: "Nome Collezione", namespace: "collectionDetails" },
    { key: "settings.save", locale: "it", value: "Salva Modifiche", namespace: "collectionDetails" },
    { key: "settings.selectKey", locale: "it", value: "Seleziona una chiave", namespace: "collectionDetails" },
    { key: "settings.title", locale: "it", value: "Impostazioni", namespace: "collectionDetails" },
    { key: "settings.valuePlaceholder", locale: "it", value: "Valore (max 35 caratteri)", namespace: "collectionDetails" },
    { key: "stats.documents", locale: "it", value: "Documenti Totali", namespace: "collectionDetails" },
    { key: "stats.title", locale: "it", value: "Statistiche", namespace: "collectionDetails" },
    { key: "title", locale: "it", value: "Dettagli Collezione", namespace: "collectionDetails" },
    { key: "marni-user-guide", locale: "en", value: "OneStore Marni", namespace: "collectionDisplay" },
    { key: "onestore-user-guide", locale: "en", value: "OneStore Diesel", namespace: "collectionDisplay" },
    { key: "marni-user-guide", locale: "it", value: "OneStore Marni", namespace: "collectionDisplay" },
    { key: "onestore-user-guide", locale: "it", value: "OneStore Diesel", namespace: "collectionDisplay" },
    { key: "documents", locale: "en", value: "Documents", namespace: "collections" },
    { key: "empty", locale: "en", value: "No collections found", namespace: "collections" },
    { key: "error.create", locale: "en", value: "Failed to create collection", namespace: "collections" },
    { key: "error.delete", locale: "en", value: "Failed to delete collection", namespace: "collections" },
    { key: "error.fetch", locale: "en", value: "Failed to fetch collections", namespace: "collections" },
    { key: "error.update", locale: "en", value: "Failed to update collection", namespace: "collections" },
    { key: "loading", locale: "en", value: "Loading collections...", namespace: "collections" },
    { key: "title", locale: "en", value: "Collections", namespace: "collections" },
    { key: "documents", locale: "it", value: "Documenti", namespace: "collections" },
    { key: "empty", locale: "it", value: "Nessuna collezione trovata", namespace: "collections" },
    { key: "error.create", locale: "it", value: "Impossibile creare la collezione", namespace: "collections" },
    { key: "error.delete", locale: "it", value: "Impossibile eliminare la collezione", namespace: "collections" },
    { key: "error.fetch", locale: "it", value: "Impossibile caricare le collezioni", namespace: "collections" },
    { key: "error.update", locale: "it", value: "Impossibile aggiornare la collezione", namespace: "collections" },
    { key: "loading", locale: "it", value: "Caricamento collezioni...", namespace: "collections" },
    { key: "title", locale: "it", value: "Collezioni", namespace: "collections" },
    { key: "documentsCount", locale: "en", value: "{count, plural, =0 {No documents} one {# document} other {# documents}}", namespace: "Common" },
    { key: "noCollectionsAvailable", locale: "en", value: "No collections available", namespace: "Common" },
    { key: "noDescription", locale: "en", value: "No description", namespace: "Common" },
    { key: "pressShiftEnter", locale: "en", value: "Press Shift + ↵ for new line", namespace: "Common" },
    { key: "selectCollection", locale: "en", value: "Please select a collection from the sidebar", namespace: "Common" },
    { key: "selectCollectionTitle", locale: "en", value: "Select a collection", namespace: "Common" },
    { key: "sendMessage", locale: "en", value: "Send Message", namespace: "Common" },
    { key: "stopGenerating", locale: "en", value: "Stop generating", namespace: "Common" },
    { key: "typeMessage", locale: "en", value: "Type your message...", namespace: "Common" },
    { key: "documentsCount", locale: "it", value: "{count, plural, =0 {Nessun documento} one {# documento} other {# documenti}}", namespace: "Common" },
    { key: "noCollectionsAvailable", locale: "it", value: "Nessuna collezione disponibile", namespace: "Common" },
    { key: "noDescription", locale: "it", value: "Nessuna descrizione", namespace: "Common" },
    { key: "pressShiftEnter", locale: "it", value: "Premi Shift + ↵ per una nuova riga", namespace: "Common" },
    { key: "selectCollection", locale: "it", value: "Seleziona una collezione dalla barra laterale", namespace: "Common" },
    { key: "selectCollectionTitle", locale: "it", value: "Seleziona una collezione", namespace: "Common" },
    { key: "sendMessage", locale: "it", value: "Invia Messaggio", namespace: "Common" },
    { key: "stopGenerating", locale: "it", value: "Interrompi generazione", namespace: "Common" },
    { key: "typeMessage", locale: "it", value: "Scrivi il tuo messaggio...", namespace: "Common" },
    { key: "introduction", locale: "en", value: "This Cookie Policy explains how ALGOSET SRL uses cookies and similar technologies on our website and applications.", namespace: "CookiePolicy" },
    { key: "lastUpdated", locale: "en", value: "Last updated: May 31, 2025", namespace: "CookiePolicy" },
    { key: "sections.changes.content", locale: "en", value: "We reserve the right to modify this Cookie Policy at any time. Any changes will be posted on this page with the update date.\n\nWe encourage you to periodically review this page to stay informed about our cookie practices.", namespace: "CookiePolicy" },
    { key: "sections.changes.title", locale: "en", value: "5. Changes to the Cookie Policy", namespace: "CookiePolicy" },
    { key: "sections.contactUs.content", locale: "en", value: "For any questions or clarifications about this Cookie Policy, you can contact us at: info@algoset.it", namespace: "CookiePolicy" },
    { key: "sections.contactUs.title", locale: "en", value: "6. Contact us", namespace: "CookiePolicy" },
    { key: "sections.cookiesWeUse.content", locale: "en", value: "We only use essential technical cookies (or \"strictly necessary\"), which enable basic functions such as authentication and session maintenance. These cookies are necessary for the proper functioning of the platform and cannot be disabled.\n\nWe do not use analytical, advertising, or profiling cookies, nor do we share data with third parties for such purposes.", namespace: "CookiePolicy" },
    { key: "sections.cookiesWeUse.title", locale: "en", value: "2. Cookies we use", namespace: "CookiePolicy" },
    { key: "sections.howToManage.content", locale: "en", value: "Since we exclusively use essential technical cookies, there is no option to disable them, as this would compromise the functioning of the platform.\n\nHowever, you can configure your browser to block or alert you about cookies. Please note that blocking all cookies will have a negative impact on the functionality of our platform, including the inability to access protected areas.", namespace: "CookiePolicy" },
    { key: "sections.howToManage.title", locale: "en", value: "4. How to manage cookies", namespace: "CookiePolicy" },
    { key: "sections.legalBasis.content", locale: "en", value: "According to EU Regulation 2016/679 (GDPR) and Directive 2002/58/EC (e-Privacy), as amended by Directive 2009/136/EC, essential technical cookies do not require prior user consent, as they are strictly necessary to provide the service.\n\nThe legal basis for the use of these cookies is Art. 6(1)(b) of the GDPR (performance of a contract or pre-contractual measures) and Art. 6(1)(f) (legitimate interest).", namespace: "CookiePolicy" },
    { key: "sections.legalBasis.title", locale: "en", value: "3. Legal basis", namespace: "CookiePolicy" },
    { key: "sections.whatAreCookies.content", locale: "en", value: "Cookies are small text files that are stored on your device when you visit a website. Cookies are widely used to make websites work or work more efficiently, as well as to provide information to the site owners.", namespace: "CookiePolicy" },
    { key: "sections.whatAreCookies.title", locale: "en", value: "1. What are cookies?", namespace: "CookiePolicy" },
    { key: "title", locale: "en", value: "Cookie Policy – ALGOSET SRL", namespace: "CookiePolicy" },
    { key: "introduction", locale: "it", value: "Questa Cookie Policy spiega come ALGOSET SRL utilizza i cookie e tecnologie simili sul sito web e applicazioni.", namespace: "CookiePolicy" },
    { key: "lastUpdated", locale: "it", value: "Ultimo aggiornamento: 31 maggio 2025", namespace: "CookiePolicy" },
    { key: "sections.changes.content", locale: "it", value: "Ci riserviamo il diritto di modificare questa Cookie Policy in qualsiasi momento. Eventuali modifiche saranno pubblicate su questa pagina con la data di aggiornamento.\n\nTi invitiamo a consultare periodicamente questa pagina per essere sempre informato sulle nostre pratiche relative ai cookie.", namespace: "CookiePolicy" },
    { key: "sections.changes.title", locale: "it", value: "5. Modifiche alla Cookie Policy", namespace: "CookiePolicy" },
    { key: "sections.contactUs.content", locale: "it", value: "Per qualsiasi domanda o chiarimento su questa Cookie Policy, puoi contattarci all'indirizzo email: info@algoset.it", namespace: "CookiePolicy" },
    { key: "sections.contactUs.title", locale: "it", value: "6. Contattaci", namespace: "CookiePolicy" },
    { key: "sections.cookiesWeUse.content", locale: "it", value: "Utilizziamo esclusivamente cookie tecnici essenziali (o \"strettamente necessari\"), che consentono le funzionalità di base come l'autenticazione e il mantenimento della sessione. Questi cookie sono necessari per il corretto funzionamento della piattaforma e non possono essere disattivati.\n\nNon utilizziamo cookie analitici, pubblicitari o di profilazione, né condividiamo dati con terze parti per tali scopi.", namespace: "CookiePolicy" },
    { key: "sections.cookiesWeUse.title", locale: "it", value: "2. Cookie utilizzati", namespace: "CookiePolicy" },
    { key: "sections.howToManage.content", locale: "it", value: "Poiché utilizziamo esclusivamente cookie tecnici essenziali, non è prevista la possibilità di disattivarli, in quanto ciò comprometterebbe il funzionamento della piattaforma.\n\nTuttavia, puoi configurare il tuo browser per bloccare o avvisarti della presenza di cookie. Ti informiamo che il blocco di tutti i cookie avrà un impatto negativo sulla funzionalità della nostra piattaforma, inclusa l'impossibilità di accedere alle aree protette.", namespace: "CookiePolicy" },
    { key: "sections.howToManage.title", locale: "it", value: "4. Gestione dei cookie", namespace: "CookiePolicy" },
    { key: "sections.legalBasis.content", locale: "it", value: "Secondo il Regolamento UE 2016/679 (GDPR) e la Direttiva 2002/58/CE (e-Privacy), modificata dalla Direttiva 2009/136/CE, i cookie tecnici essenziali non richiedono il consenso preventivo dell'utente, in quanto strettamente necessari a fornire il servizio.\n\nLa base giuridica per l'uso di tali cookie è l'art. 6(1)(b) del GDPR (esecuzione di un contratto o misure precontrattuali) e l'art. 6(1)(f) (interesse legittimo).", namespace: "CookiePolicy" },
    { key: "sections.legalBasis.title", locale: "it", value: "3. Base giuridica", namespace: "CookiePolicy" },
    { key: "sections.whatAreCookies.content", locale: "it", value: "I cookie sono piccoli file di testo che vengono archiviati sul tuo dispositivo quando visiti un sito web. I cookie vengono ampiamente utilizzati per far funzionare i siti web o per farli funzionare in modo più efficiente, nonché per fornire informazioni ai proprietari del sito.", namespace: "CookiePolicy" },
    { key: "sections.whatAreCookies.title", locale: "it", value: "1. Cosa sono i cookie?", namespace: "CookiePolicy" },
    { key: "title", locale: "it", value: "Cookie Policy – ALGOSET SRL", namespace: "CookiePolicy" },
    { key: "attributes.addField", locale: "en", value: "Add Attribute", namespace: "createCollection" },
    { key: "attributes.inUse", locale: "en", value: "in use", namespace: "createCollection" },
    { key: "attributes.label", locale: "en", value: "Attributes", namespace: "createCollection" },
    { key: "attributes.typePlaceholder", locale: "en", value: "Select attribute type", namespace: "createCollection" },
    { key: "attributes.valuePlaceholder", locale: "en", value: "Value", namespace: "createCollection" },
    { key: "button", locale: "en", value: "Create Collection", namespace: "createCollection" },
    { key: "cancel", locale: "en", value: "Cancel", namespace: "createCollection" },
    { key: "description.label", locale: "en", value: "Description", namespace: "createCollection" },
    { key: "description.placeholder", locale: "en", value: "Add a description for the collection...", namespace: "createCollection" },
    { key: "dialogDescription", locale: "en", value: "Create a new collection to organize your documents. Provide a unique name and optional attributes to categorize your content effectively.", namespace: "createCollection" },
    { key: "dialogTitle", locale: "en", value: "Create New Collection", namespace: "createCollection" },
    { key: "name.label", locale: "en", value: "Collection Name", namespace: "createCollection" },
    { key: "name.placeholder", locale: "en", value: "Insert the collection name...", namespace: "createCollection" },
    { key: "submit", locale: "en", value: "Create", namespace: "createCollection" },
    { key: "attributes.addField", locale: "it", value: "Aggiungi Attributo", namespace: "createCollection" },
    { key: "attributes.inUse", locale: "it", value: "in uso", namespace: "createCollection" },
    { key: "attributes.label", locale: "it", value: "Attributi", namespace: "createCollection" },
    { key: "attributes.typePlaceholder", locale: "it", value: "Seleziona tipo attributo", namespace: "createCollection" },
    { key: "attributes.valuePlaceholder", locale: "it", value: "Valore", namespace: "createCollection" },
    { key: "button", locale: "it", value: "Crea Collezione", namespace: "createCollection" },
    { key: "cancel", locale: "it", value: "Annulla", namespace: "createCollection" },
    { key: "description.label", locale: "it", value: "Descrizione", namespace: "createCollection" },
    { key: "description.placeholder", locale: "it", value: "Inserisci una descrizione per la collezione...", namespace: "createCollection" },
    { key: "dialogDescription", locale: "it", value: "Crea una nuova collezione per organizzare i tuoi documenti. Fornisci un nome univoco e attributi opzionali per categorizzare efficacemente i tuoi contenuti.", namespace: "createCollection" },
    { key: "dialogTitle", locale: "it", value: "Crea Nuova Collezione", namespace: "createCollection" },
    { key: "name.label", locale: "it", value: "Nome Collezione", namespace: "createCollection" },
    { key: "name.placeholder", locale: "it", value: "Inserisci il nome della collezione", namespace: "createCollection" },
    { key: "submit", locale: "it", value: "Crea", namespace: "createCollection" },
    { key: "cancelButton", locale: "en", value: "Cancel", namespace: "deleteAlert" },
    { key: "confirmPlaceholder", locale: "en", value: "Type {action} to confirm", namespace: "deleteAlert" },
    { key: "confirmText", locale: "en", value: "Please type {action} to confirm:", namespace: "deleteAlert" },
    { key: "deleteButton", locale: "en", value: "Delete", namespace: "deleteAlert" },
    { key: "description", locale: "en", value: "This action cannot be undone. This will permanently delete the collection \"{name}\" and all its documents.", namespace: "deleteAlert" },
    { key: "title", locale: "en", value: "Are you absolutely sure?", namespace: "deleteAlert" },
    { key: "cancelButton", locale: "it", value: "Annulla", namespace: "deleteAlert" },
    { key: "confirmPlaceholder", locale: "it", value: "Digita {action} per confermare", namespace: "deleteAlert" },
    { key: "confirmText", locale: "it", value: "Digita {action} per confermare:", namespace: "deleteAlert" },
    { key: "deleteButton", locale: "it", value: "Elimina", namespace: "deleteAlert" },
    { key: "description", locale: "it", value: "Questa azione non può essere annullata. Eliminerà permanentemente la collezione \"{name}\" e tutti i suoi documenti.", namespace: "deleteAlert" },
    { key: "title", locale: "it", value: "Sei assolutamente sicuro?", namespace: "deleteAlert" },
    { key: "applicationErrorTitle", locale: "en", value: "Application Error", namespace: "Errors" },
    { key: "authenticationFailed", locale: "en", value: "Authentication Failed", namespace: "Errors" },
    { key: "defaultMessage", locale: "en", value: "An unexpected error occurred while processing your request.", namespace: "Errors" },
    { key: "defaultTitle", locale: "en", value: "Error Occurred", namespace: "Errors" },
    { key: "genericError", locale: "en", value: "An error occurred", namespace: "Errors" },
    { key: "hideDetails", locale: "en", value: "Hide Details", namespace: "Errors" },
    { key: "networkError", locale: "en", value: "Network Error", namespace: "Errors" },
    { key: "okButton", locale: "en", value: "OK", namespace: "Errors" },
    { key: "permissionDenied", locale: "en", value: "Permission Denied", namespace: "Errors" },
    { key: "serverError", locale: "en", value: "Server Error", namespace: "Errors" },
    { key: "showDetails", locale: "en", value: "Show Details", namespace: "Errors" },
    { key: "technicalDetails", locale: "en", value: "Technical Details", namespace: "Errors" },
    { key: "unexpectedError", locale: "en", value: "An unexpected error occurred", namespace: "Errors" },
    { key: "unknownError", locale: "en", value: "Unknown error", namespace: "Errors" },
    { key: "applicationErrorTitle", locale: "it", value: "Errore Applicazione", namespace: "Errors" },
    { key: "authenticationFailed", locale: "it", value: "Autenticazione Fallita", namespace: "Errors" },
    { key: "defaultMessage", locale: "it", value: "Si è verificato un errore imprevisto durante l'elaborazione della richiesta.", namespace: "Errors" },
    { key: "defaultTitle", locale: "it", value: "Errore", namespace: "Errors" },
    { key: "genericError", locale: "it", value: "Si è verificato un errore", namespace: "Errors" },
    { key: "hideDetails", locale: "it", value: "Nascondi Dettagli", namespace: "Errors" },
    { key: "networkError", locale: "it", value: "Errore di Rete", namespace: "Errors" },
    { key: "okButton", locale: "it", value: "OK", namespace: "Errors" },
    { key: "permissionDenied", locale: "it", value: "Permesso Negato", namespace: "Errors" },
    { key: "serverError", locale: "it", value: "Errore del Server", namespace: "Errors" },
    { key: "showDetails", locale: "it", value: "Mostra Dettagli", namespace: "Errors" },
    { key: "technicalDetails", locale: "it", value: "Dettagli Tecnici", namespace: "Errors" },
    { key: "unexpectedError", locale: "it", value: "Si è verificato un errore imprevisto", namespace: "Errors" },
    { key: "unknownError", locale: "it", value: "Errore sconosciuto", namespace: "Errors" },
    { key: "allRightsReserved", locale: "en", value: "All rights reserved", namespace: "Footer" },
    { key: "closeCookiePolicy", locale: "en", value: "Close", namespace: "Footer" },
    { key: "closePrivacyPolicy", locale: "en", value: "Close", namespace: "Footer" },
    { key: "companyAddress", locale: "en", value: "Via Lago d'Iseo 53, 36100 Vicenza, Italy", namespace: "Footer" },
    { key: "companyDescription", locale: "en", value: "We create innovative digital solutions with cutting-edge technologies.", namespace: "Footer" },
    { key: "companyVatRea", locale: "en", value: "VAT IT03976390249 — REA VI-369285 — PEC: algoset@legalmail.it", namespace: "Footer" },
    { key: "cookiePolicy", locale: "en", value: "Cookie Policy", namespace: "Footer" },
    { key: "copyright", locale: "en", value: "© {year} ALGOSET SRL — VAT IT03976390249 — Registered office: Via Lago d'Iseo 53, 36100 Vicenza, Italy — Certified email (PEC): algoset@legalmail.it", namespace: "Footer" },
    { key: "legals", locale: "en", value: "Legal Information", namespace: "Footer" },
    { key: "privacyPolicy", locale: "en", value: "Privacy Policy", namespace: "Footer" },
    { key: "viewCookiePolicy", locale: "en", value: "View Cookie Policy", namespace: "Footer" },
    { key: "viewPrivacyPolicy", locale: "en", value: "View Privacy Policy", namespace: "Footer" },
    { key: "allRightsReserved", locale: "it", value: "Tutti i diritti riservati", namespace: "Footer" },
    { key: "closeCookiePolicy", locale: "it", value: "Chiudi", namespace: "Footer" },
    { key: "closePrivacyPolicy", locale: "it", value: "Chiudi", namespace: "Footer" },
    { key: "companyAddress", locale: "it", value: "Via Lago d'Iseo 53, 36100 Vicenza (VI)", namespace: "Footer" },
    { key: "companyDescription", locale: "it", value: "Creiamo soluzioni digitali innovative con tecnologie all'avanguardia.", namespace: "Footer" },
    { key: "companyVatRea", locale: "it", value: "P.IVA 03976390249 — REA VI-369285 — PEC: algoset@legalmail.it", namespace: "Footer" },
    { key: "cookiePolicy", locale: "it", value: "Cookie Policy", namespace: "Footer" },
    { key: "copyright", locale: "it", value: "© {year} ALGOSET SRL — P.IVA 03976390249 — REA VI-369285 — Sede legale: Via Lago d'Iseo 53, 36100 Vicenza (VI) — PEC: algoset@legalmail.it", namespace: "Footer" },
    { key: "legals", locale: "it", value: "Informazioni legali", namespace: "Footer" },
    { key: "privacyPolicy", locale: "it", value: "Privacy Policy", namespace: "Footer" },
    { key: "viewCookiePolicy", locale: "it", value: "Visualizza Cookie Policy", namespace: "Footer" },
    { key: "viewPrivacyPolicy", locale: "it", value: "Visualizza Privacy Policy", namespace: "Footer" },
    { key: "about", locale: "en", value: "About", namespace: "HomePage" },
    { key: "appName", locale: "en", value: "DOCUMINDS", namespace: "HomePage" },
    { key: "gotoDashboard", locale: "en", value: "Go to Dashboard", namespace: "HomePage" },
    { key: "subtitle", locale: "en", value: "Chat with your documents and unlock their hidden insights. Our secure, AI-powered search transforms complex information into natural conversations, letting you explore your private data through simple questions. Get precise answers, discover connections, and make your documents work smarter for you.", namespace: "HomePage" },
    { key: "title", locale: "en", value: "Documents That Understand You!", namespace: "HomePage" },
    { key: "about", locale: "it", value: "Chi siamo", namespace: "HomePage" },
    { key: "appName", locale: "it", value: "DOCUMINDS", namespace: "HomePage" },
    { key: "gotoDashboard", locale: "it", value: "Vai al Pannello di Amministrazione", namespace: "HomePage" },
    { key: "subtitle", locale: "it", value: "Chat con i tuoi documenti e scopri le loro insights nascosti. Il nostro motore di ricerca privato basato su RAG trasforma le informazioni complesse in conversazioni naturali, permettendoti di esplorare i tuoi dati privati attraverso semplici domande. Ottieni risposte precise, scopri connessioni e rendi i tuoi documenti più intelligenti per te.", namespace: "HomePage" },
    { key: "title", locale: "it", value: "Documents That Understand You!", namespace: "HomePage" },
    { key: "en", locale: "en", value: "English", namespace: "Languages" },
    { key: "it", locale: "en", value: "Italian", namespace: "Languages" },
    { key: "switchLanguage", locale: "en", value: "Switch language", namespace: "Languages" },
    { key: "en", locale: "it", value: "Inglese", namespace: "Languages" },
    { key: "it", locale: "it", value: "Italiano", namespace: "Languages" },
    { key: "switchLanguage", locale: "it", value: "Cambia lingua", namespace: "Languages" },
    { key: "authenticating", locale: "en", value: "Authenticating", namespace: "Login" },
    { key: "preparingConnection", locale: "en", value: "Preparing your secure connection...", namespace: "Login" },
    { key: "redirectingToLogin", locale: "en", value: "Redirecting to secure login...", namespace: "Login" },
    { key: "authenticating", locale: "it", value: "Autenticazione in corso", namespace: "Login" },
    { key: "preparingConnection", locale: "it", value: "Preparazione della connessione sicura...", namespace: "Login" },
    { key: "redirectingToLogin", locale: "it", value: "Reindirizzamento al login sicuro...", namespace: "Login" },
    { key: "description", locale: "en", value: "A Chat-Based Private Document Search with RAG", namespace: "Metadata" },
    { key: "title", locale: "en", value: "Welcome to Documinds", namespace: "Metadata" },
    { key: "description", locale: "it", value: "Un motore di ricerca documentale privato basato su RAG", namespace: "Metadata" },
    { key: "title", locale: "it", value: "Documinds", namespace: "Metadata" },
    { key: "billing", locale: "en", value: "Billing", namespace: "Navigation" },
    { key: "clearChat", locale: "en", value: "Clear chat history", namespace: "Navigation" },
    { key: "dashboard", locale: "en", value: "Dashboard", namespace: "Navigation" },
    { key: "documentation", locale: "en", value: "Documentation", namespace: "Navigation" },
    { key: "general", locale: "en", value: "General", namespace: "Navigation" },
    { key: "limits", locale: "en", value: "Limits", namespace: "Navigation" },
    { key: "newChat", locale: "en", value: "New Chat", namespace: "Navigation" },
    { key: "platform", locale: "en", value: "Platform", namespace: "Navigation" },
    { key: "settings", locale: "en", value: "Settings", namespace: "Navigation" },
    { key: "team", locale: "en", value: "Team", namespace: "Navigation" },
    { key: "toggleSidebar", locale: "en", value: "Toggle Sidebar", namespace: "Navigation" },
    { key: "users", locale: "en", value: "Users", namespace: "Navigation" },
    { key: "billing", locale: "it", value: "Fatturazione", namespace: "Navigation" },
    { key: "clearChat", locale: "it", value: "Cancella cronologia chat", namespace: "Navigation" },
    { key: "dashboard", locale: "it", value: "Dashboard", namespace: "Navigation" },
    { key: "documentation", locale: "it", value: "Documentazione", namespace: "Navigation" },
    { key: "general", locale: "it", value: "Generale", namespace: "Navigation" },
    { key: "limits", locale: "it", value: "Limiti", namespace: "Navigation" },
    { key: "newChat", locale: "it", value: "Nuova Chat", namespace: "Navigation" },
    { key: "platform", locale: "it", value: "Piattaforma", namespace: "Navigation" },
    { key: "settings", locale: "it", value: "Impostazioni", namespace: "Navigation" },
    { key: "team", locale: "it", value: "Team", namespace: "Navigation" },
    { key: "toggleSidebar", locale: "it", value: "Attiva/Disattiva Barra Laterale", namespace: "Navigation" },
    { key: "users", locale: "it", value: "Utenti", namespace: "Navigation" },
    { key: "introduction", locale: "en", value: "This privacy notice is provided pursuant to Articles 13 and 14 of EU Regulation 2016/679 (GDPR) to users accessing the SaaS platform provided by ALGOSET SRL, accessible exclusively through authentication.", namespace: "PrivacyPolicy" },
    { key: "lastUpdated", locale: "en", value: "Last updated: May 31, 2025", namespace: "PrivacyPolicy" },
    { key: "sections.changes.content", locale: "en", value: "ALGOSET SRL reserves the right to update this privacy notice. In case of significant changes, users will be informed through appropriate channels (e.g. email or platform notification).", namespace: "PrivacyPolicy" },
    { key: "sections.changes.title", locale: "en", value: "10. Changes to this Privacy Notice", namespace: "PrivacyPolicy" },
    { key: "sections.controller.content", locale: "en", value: "The data controller is:\nALGOSET SRL\nVia Lago d'Iseo 53, 36100 Vicenza (VI)\nVAT IT03976390249 - REA VI-369285\nEmail: info@algoset.it", namespace: "PrivacyPolicy" },
    { key: "sections.controller.title", locale: "en", value: "1. Data Controller", namespace: "PrivacyPolicy" },
    { key: "sections.cookies.content", locale: "en", value: "The platform exclusively uses technical session cookies, necessary to ensure the security and continuity of authentication.\nThere are no profiling cookies or third-party cookies.\nConsequently, user consent is not required, nor is a cookie banner necessary.", namespace: "PrivacyPolicy" },
    { key: "sections.cookies.title", locale: "en", value: "9. Cookies", namespace: "PrivacyPolicy" },
    { key: "sections.dataTypes.content", locale: "en", value: "During the use of the platform, the following personal data is processed:\n- First and last name (if provided through Identity Provider)\n- Business email address\n- Username or user ID\n- Session cookies (necessary for login functionality)", namespace: "PrivacyPolicy" },
    { key: "sections.dataTypes.title", locale: "en", value: "3. Types of Data Collected", namespace: "PrivacyPolicy" },
    { key: "sections.legalBasis.content", locale: "en", value: "Data processing is based on the performance of a contract (art. 6, par. 1, letter b of GDPR), as it is necessary to allow authenticated access to the platform by users of client companies.", namespace: "PrivacyPolicy" },
    { key: "sections.legalBasis.title", locale: "en", value: "4. Legal Basis", namespace: "PrivacyPolicy" },
    { key: "sections.purposes.content", locale: "en", value: "Users' personal data is processed exclusively to allow access and use of the SaaS service, which enables consultation and search of technical company documentation. No marketing, profiling, or behavioral analysis activities are carried out.", namespace: "PrivacyPolicy" },
    { key: "sections.purposes.title", locale: "en", value: "2. Processing Purposes", namespace: "PrivacyPolicy" },
    { key: "sections.recipients.content", locale: "en", value: "Data is not disclosed to third parties, except to service providers strictly necessary for the operation of the platform:\n- Amazon Web Services (AWS) – cloud hosting\n- Keycloak – identity management system\nThese entities act as data processors (Art. 28 GDPR), according to contractual agreements compliant with GDPR.", namespace: "PrivacyPolicy" },
    { key: "sections.recipients.title", locale: "en", value: "6. Data Recipients", namespace: "PrivacyPolicy" },
    { key: "sections.retention.content", locale: "en", value: "Personal data is kept for the duration of the contractual relationship with the client company, and for a maximum of 12 months after account deactivation, unless different legal obligations apply.", namespace: "PrivacyPolicy" },
    { key: "sections.retention.title", locale: "en", value: "7. Retention Period", namespace: "PrivacyPolicy" },
    { key: "sections.rights.content", locale: "en", value: "Under GDPR, the user has the right to:\n- access their personal data\n- request rectification or erasure\n- restrict or object to processing\n- request data portability\nRequests can be sent to: info@algoset.it", namespace: "PrivacyPolicy" },
    { key: "sections.rights.title", locale: "en", value: "8. Data Subject Rights", namespace: "PrivacyPolicy" },
    { key: "sections.security.content", locale: "en", value: "Data is processed using IT tools in compliance with the principles of lawfulness, fairness, and transparency.\nThe infrastructure is hosted on Amazon Web Services (AWS) – EU region (Frankfurt). Data is not transferred outside the European Economic Area (EEA).\nAll communications take place via encrypted connections (HTTPS). Authentication data is managed through Keycloak, with updated security policies.", namespace: "PrivacyPolicy" },
    { key: "sections.security.title", locale: "en", value: "5. Processing Methods and Security", namespace: "PrivacyPolicy" },
    { key: "title", locale: "en", value: "Privacy Policy – ALGOSET SRL", namespace: "PrivacyPolicy" },
    { key: "introduction", locale: "it", value: "La presente informativa è resa ai sensi degli articoli 13 e 14 del Regolamento UE 2016/679 (GDPR) agli utenti che accedono alla piattaforma SaaS fornita da ALGOSET SRL, accessibile esclusivamente tramite autenticazione.", namespace: "PrivacyPolicy" },
    { key: "lastUpdated", locale: "it", value: "Ultimo aggiornamento: 31 maggio 2025", namespace: "PrivacyPolicy" },
    { key: "sections.changes.content", locale: "it", value: "ALGOSET SRL si riserva il diritto di aggiornare la presente informativa. In caso di modifiche rilevanti, gli utenti verranno informati tramite i canali appropriati (es. email o notifica in piattaforma).", namespace: "PrivacyPolicy" },
    { key: "sections.changes.title", locale: "it", value: "10. Modifiche alla presente informativa", namespace: "PrivacyPolicy" },
    { key: "sections.controller.content", locale: "it", value: "Il titolare del trattamento è:\nALGOSET SRL\nVia Lago d'Iseo 53, 36100 Vicenza (VI)\nP.IVA 03976390249 - REA VI-369285\nEmail: info@algoset.it", namespace: "PrivacyPolicy" },
    { key: "sections.controller.title", locale: "it", value: "1. Titolare del trattamento", namespace: "PrivacyPolicy" },
    { key: "sections.cookies.content", locale: "it", value: "La piattaforma utilizza esclusivamente cookie tecnici di sessione, necessari per garantire la sicurezza e la continuità dell'autenticazione.\nNon sono presenti cookie di profilazione né cookie di terze parti.\nDi conseguenza, non è richiesto il consenso dell'utente, né è necessario il banner cookie.", namespace: "PrivacyPolicy" },
    { key: "sections.cookies.title", locale: "it", value: "9. Cookie", namespace: "PrivacyPolicy" },
    { key: "sections.dataTypes.content", locale: "it", value: "Durante l'utilizzo della piattaforma vengono trattati i seguenti dati personali:\n- Nome e cognome (se forniti tramite Identity Provider)\n- Indirizzo email aziendale\n- Username o ID utente\n- Cookie di sessione (necessari al funzionamento del login)", namespace: "PrivacyPolicy" },
    { key: "sections.dataTypes.title", locale: "it", value: "3. Tipologia di dati raccolti", namespace: "PrivacyPolicy" },
    { key: "sections.legalBasis.content", locale: "it", value: "Il trattamento dei dati si basa sull'esecuzione del contratto (art. 6, par. 1, lett. b del GDPR), in quanto necessario per consentire l'accesso autenticato alla piattaforma da parte degli utenti delle aziende clienti.", namespace: "PrivacyPolicy" },
    { key: "sections.legalBasis.title", locale: "it", value: "4. Base giuridica", namespace: "PrivacyPolicy" },
    { key: "sections.purposes.content", locale: "it", value: "I dati personali degli utenti vengono trattati esclusivamente per consentire l'accesso e l'utilizzo del servizio SaaS, che permette la consultazione e ricerca di documentazione tecnica aziendale. Non viene effettuata alcuna attività di marketing, profilazione o analisi comportamentale.", namespace: "PrivacyPolicy" },
    { key: "sections.purposes.title", locale: "it", value: "2. Finalità del trattamento", namespace: "PrivacyPolicy" },
    { key: "sections.recipients.content", locale: "it", value: "I dati non vengono comunicati a soggetti terzi, salvo ai fornitori di servizi strettamente necessari al funzionamento della piattaforma:\n- Amazon Web Services (AWS) – hosting cloud\n- Keycloak – sistema di gestione identità\nQuesti soggetti agiscono in qualità di responsabili del trattamento (Art. 28 GDPR), secondo accordi contrattuali conformi al GDPR.", namespace: "PrivacyPolicy" },
    { key: "sections.recipients.title", locale: "it", value: "6. Destinatari dei dati", namespace: "PrivacyPolicy" },
    { key: "sections.retention.content", locale: "it", value: "I dati personali vengono conservati per tutta la durata del rapporto contrattuale con l'azienda cliente, e per un massimo di 12 mesi dopo la disattivazione dell'account, salvo obblighi legali differenti.", namespace: "PrivacyPolicy" },
    { key: "sections.retention.title", locale: "it", value: "7. Durata della conservazione", namespace: "PrivacyPolicy" },
    { key: "sections.rights.content", locale: "it", value: "Ai sensi del GDPR, l'utente ha diritto di:\n- accedere ai propri dati personali\n- chiedere la rettifica o la cancellazione\n- limitare o opporsi al trattamento\n- richiedere la portabilità dei dati\nLe richieste possono essere inviate a: info@algoset.it", namespace: "PrivacyPolicy" },
    { key: "sections.rights.title", locale: "it", value: "8. Diritti dell'interessato", namespace: "PrivacyPolicy" },
    { key: "sections.security.content", locale: "it", value: "I dati sono trattati con strumenti informatici nel rispetto dei principi di liceità, correttezza e trasparenza.\nL'infrastruttura è ospitata su Amazon Web Services (AWS) – regione UE (Francoforte). I dati non vengono trasferiti al di fuori dello Spazio Economico Europeo (SEE).\nTutte le comunicazioni avvengono tramite connessioni cifrate (HTTPS). I dati di autenticazione sono gestiti tramite Keycloak, con policy di sicurezza aggiornate.", namespace: "PrivacyPolicy" },
    { key: "sections.security.title", locale: "it", value: "5. Modalità di trattamento e sicurezza", namespace: "PrivacyPolicy" },
    { key: "title", locale: "it", value: "Privacy Policy – ALGOSET SRL", namespace: "PrivacyPolicy" },
    { key: "cancel", locale: "en", value: "Cancel", namespace: "SettingCard" },
    { key: "company", locale: "en", value: "Company", namespace: "SettingCard" },
    { key: "configure", locale: "en", value: "Configure", namespace: "SettingCard" },
    { key: "currentValue", locale: "en", value: "Current Value", namespace: "SettingCard" },
    { key: "encrypted", locale: "en", value: "Encrypted", namespace: "SettingCard" },
    { key: "encryptedNote", locale: "en", value: "This value is encrypted and securely stored.", namespace: "SettingCard" },
    { key: "flowIdNote", locale: "en", value: "Flow ID format: alphanumeric with hyphens (e.g., flow-abc-123)", namespace: "SettingCard" },
    { key: "notConfigured", locale: "en", value: "Not configured", namespace: "SettingCard" },
    { key: "placeholders.apiKey", locale: "en", value: "Enter API key...", namespace: "SettingCard" },
    { key: "placeholders.chatFlowId", locale: "en", value: "e.g., chat-flow-123", namespace: "SettingCard" },
    { key: "placeholders.default", locale: "en", value: "Enter value...", namespace: "SettingCard" },
    { key: "placeholders.embeddingsFlowId", locale: "en", value: "e.g., embeddings-flow-456", namespace: "SettingCard" },
    { key: "save", locale: "en", value: "Save", namespace: "SettingCard" },
    { key: "saving", locale: "en", value: "Saving...", namespace: "SettingCard" },
    { key: "update", locale: "en", value: "Update", namespace: "SettingCard" },
    { key: "cancel", locale: "it", value: "Annulla", namespace: "SettingCard" },
    { key: "company", locale: "it", value: "Azienda", namespace: "SettingCard" },
    { key: "configure", locale: "it", value: "Configura", namespace: "SettingCard" },
    { key: "currentValue", locale: "it", value: "Valore Corrente", namespace: "SettingCard" },
    { key: "encrypted", locale: "it", value: "Crittografato", namespace: "SettingCard" },
    { key: "encryptedNote", locale: "it", value: "Questo valore è crittografato e memorizzato in modo sicuro.", namespace: "SettingCard" },
    { key: "flowIdNote", locale: "it", value: "Formato ID flusso: alfanumerico con trattini (es. flow-abc-123)", namespace: "SettingCard" },
    { key: "notConfigured", locale: "it", value: "Non configurato", namespace: "SettingCard" },
    { key: "placeholders.apiKey", locale: "it", value: "Inserisci chiave API...", namespace: "SettingCard" },
    { key: "placeholders.chatFlowId", locale: "it", value: "es. chat-flow-123", namespace: "SettingCard" },
    { key: "placeholders.default", locale: "it", value: "Inserisci valore...", namespace: "SettingCard" },
    { key: "placeholders.embeddingsFlowId", locale: "it", value: "es. embeddings-flow-456", namespace: "SettingCard" },
    { key: "save", locale: "it", value: "Salva", namespace: "SettingCard" },
    { key: "saving", locale: "it", value: "Salvataggio...", namespace: "SettingCard" },
    { key: "update", locale: "it", value: "Aggiorna", namespace: "SettingCard" },
    { key: "loading", locale: "en", value: "Loading...", namespace: "UI" },
    { key: "scrollToBottom", locale: "en", value: "Scroll to bottom", namespace: "UI" },
    { key: "toggleSidebar", locale: "en", value: "Toggle Sidebar", namespace: "UI" },
    { key: "value", locale: "en", value: "Value", namespace: "UI" },
    { key: "loading", locale: "it", value: "Caricamento...", namespace: "UI" },
    { key: "scrollToBottom", locale: "it", value: "Scorri in basso", namespace: "UI" },
    { key: "toggleSidebar", locale: "it", value: "Attiva/Disattiva Barra Laterale", namespace: "UI" },
    { key: "value", locale: "it", value: "Valore", namespace: "UI" },
    { key: "collectionName", locale: "en", value: "Collection Name", namespace: "Upload" },
    { key: "docs", locale: "en", value: "docs", namespace: "Upload" },
    { key: "dragDropFiles", locale: "en", value: "Drag 'n' drop some files here, or click to select files", namespace: "Upload" },
    { key: "dropFilesHere", locale: "en", value: "Drop the files here...", namespace: "Upload" },
    { key: "failedToInitialize", locale: "en", value: "Failed to initialize upload stream", namespace: "Upload" },
    { key: "failedToUpload", locale: "en", value: "Failed to upload documents", namespace: "Upload" },
    { key: "pleaseSelectFiles", locale: "en", value: "Please select files to upload", namespace: "Upload" },
    { key: "selectCollection", locale: "en", value: "Select a collection", namespace: "Upload" },
    { key: "selectedFiles", locale: "en", value: "Selected files:", namespace: "Upload" },
    { key: "supportedFormats", locale: "en", value: "Supported formats: PDF, DOC, DOCX, TXT", namespace: "Upload" },
    { key: "title", locale: "en", value: "Upload Documents", namespace: "Upload" },
    { key: "uploadDocuments", locale: "en", value: "Upload Documents", namespace: "Upload" },
    { key: "uploading", locale: "en", value: "Uploading...", namespace: "Upload" },
    { key: "collectionName", locale: "it", value: "Nome Collezione", namespace: "Upload" },
    { key: "docs", locale: "it", value: "docs", namespace: "Upload" },
    { key: "dragDropFiles", locale: "it", value: "Trascina i file qui, oppure clicca per selezionare i file", namespace: "Upload" },
    { key: "dropFilesHere", locale: "it", value: "Rilascia i file qui...", namespace: "Upload" },
    { key: "failedToInitialize", locale: "it", value: "Impossibile inizializzare il flusso di caricamento", namespace: "Upload" },
    { key: "failedToUpload", locale: "it", value: "Impossibile caricare i documenti", namespace: "Upload" },
    { key: "pleaseSelectFiles", locale: "it", value: "Seleziona i file da caricare", namespace: "Upload" },
    { key: "selectCollection", locale: "it", value: "Seleziona una collezione", namespace: "Upload" },
    { key: "selectedFiles", locale: "it", value: "File selezionati:", namespace: "Upload" },
    { key: "supportedFormats", locale: "it", value: "Formati supportati: PDF, DOC, DOCX, TXT", namespace: "Upload" },
    { key: "title", locale: "it", value: "Carica Documenti", namespace: "Upload" },
    { key: "uploadDocuments", locale: "it", value: "Carica Documenti", namespace: "Upload" },
    { key: "uploading", locale: "it", value: "Caricamento...", namespace: "Upload" },
    { key: "account", locale: "en", value: "Account", namespace: "UserNav" },
    { key: "billing", locale: "en", value: "Billing", namespace: "UserNav" },
    { key: "logout", locale: "en", value: "Log out", namespace: "UserNav" },
    { key: "notifications", locale: "en", value: "Notifications", namespace: "UserNav" },
    { key: "profile", locale: "en", value: "Profile", namespace: "UserNav" },
    { key: "settings", locale: "en", value: "Settings", namespace: "UserNav" },
    { key: "upgradeToPro", locale: "en", value: "Upgrade to Pro", namespace: "UserNav" },
    { key: "account", locale: "it", value: "Account", namespace: "UserNav" },
    { key: "billing", locale: "it", value: "Fatturazione", namespace: "UserNav" },
    { key: "logout", locale: "it", value: "Esci", namespace: "UserNav" },
    { key: "notifications", locale: "it", value: "Notifiche", namespace: "UserNav" },
    { key: "profile", locale: "it", value: "Profilo", namespace: "UserNav" },
    { key: "settings", locale: "it", value: "Impostazioni", namespace: "UserNav" },
    { key: "upgradeToPro", locale: "it", value: "Passa a Pro", namespace: "UserNav" },
    { key: "collection.metadata.key.required", locale: "en", value: "Please select a key", namespace: "validation" },
    { key: "collection.metadata.value.empty", locale: "en", value: "Value cannot be empty", namespace: "validation" },
    { key: "collection.metadata.value.max", locale: "en", value: "Value must be less than {max} characters", namespace: "validation" },
    { key: "collection.metadata.value.required", locale: "en", value: "Value is required", namespace: "validation" },
    { key: "collection.name.format", locale: "en", value: "Only lowercase letters, numbers, and hyphens are allowed", namespace: "validation" },
    { key: "collection.name.max", locale: "en", value: "Collection name must be less than {max} characters", namespace: "validation" },
    { key: "collection.name.min", locale: "en", value: "Collection name must be at least {min} characters", namespace: "validation" },
    { key: "collection.metadata.key.required", locale: "it", value: "Seleziona una chiave", namespace: "validation" },
    { key: "collection.metadata.value.empty", locale: "it", value: "Il valore non può essere vuoto", namespace: "validation" },
    { key: "collection.metadata.value.max", locale: "it", value: "Il valore deve contenere meno di {max} caratteri", namespace: "validation" },
    { key: "collection.metadata.value.required", locale: "it", value: "Il valore è obbligatorio", namespace: "validation" },
    { key: "collection.name.format", locale: "it", value: "Sono consentiti solo lettere minuscole, numeri e trattini", namespace: "validation" },
    { key: "collection.name.max", locale: "it", value: "Il nome della collezione deve contenere meno di {max} caratteri", namespace: "validation" },
    { key: "collection.name.min", locale: "it", value: "Il nome della collezione deve contenere almeno {min} caratteri", namespace: "validation" },
  ];

  console.log("Seeding translations...");

  for (const translation of translations) {
    await prisma.translation.upsert({
      where: {
        key_locale_namespace: {
          key: translation.key,
          locale: translation.locale,
          namespace: translation.namespace,
        },
      },
      update: {
        value: translation.value,
      },
      create: translation,
    });
  }

  console.log("Translation seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
