
services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - documinds-net

  # chromadb:
  #   container_name: chromadb
  #   image: chromadb/chroma:latest
  #   volumes:
  #     - chromadb-data:/chroma/data
  #     - chromadb-config:/chroma/config
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - CHROMA_SERVER_AUTH_CREDENTIALS_FILE=/chroma/config/auth.json
  #     - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.basic.BasicAuthCredentialsProvider
  #     - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.basic.BasicAuthServerProvider
  #     - PERSIST_DIRECTORY=/chroma/data
  #   networks:
  #     - documinds-net

  # Unstructured API
  # unstructured-api:
  #   container_name: unstructured-api
  #   image: downloads.unstructured.io/unstructured-io/unstructured-api:0.0.80
  #   platform: linux/arm64
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - LOG_LEVEL=DEBUG
  #     - METRICS_ENABLED=false
  #     - VALIDATE_TYPES=false
  #   command: ["--port", "8000", "--host", "0.0.0.0"]
  #   mem_limit: 6g  # Set max memory usage to 4GB
  #   cpus: "4.0"     # Allocate 2 CPU cores
  #   restart: unless-stopped
  #   networks:
  #     - documinds-net

  # Langflow
  langflow:
    container_name: langflow
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    env_file:
      - .env.langflow
    # environment:
    #   - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
    #   # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    #   - LANGFLOW_CONFIG_DIR=app/langflow
    volumes:
      - langflow-data:/app/langflow
    networks:
      - documinds-net

  # Postgres
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - documinds-net

  documinds-app:
    image: ghcr.io/apercky/documinds:${VERSION:-latest}
    container_name: documinds-app
    env_file:
      - .env.documinds
    volumes:
      - ./certs:/app/certs
    expose:
      - "3000"
    networks:
      - documinds-net

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - documinds-app
    networks:
      - documinds-net

volumes:
  langflow-postgres:
    driver: local
    driver_opts:
      type: none
      device: "${LANGFLOW_POSTGRES_PATH}"
      o: bind

  langflow-data:
    driver: local
    driver_opts:
      type: none
      device: "${LANGFLOW_DATA_PATH}"
      o: bind

  qdrant-storage:
    driver: local
    driver_opts:
      type: none
      device: "${QDRANT_STORAGE_PATH}"
      o: bind

  # chromadb-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "${CHROMA_DATA_PATH}"
  #     o: bind

  # chromadb-config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "${CHROMA_CONFIG_PATH}"
  #     o: bind

networks:
  documinds-net:
    driver: bridge
