name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}  # semantic-release usa sempre questa variabile
        run: |
          echo "✔️  Using PAT to authenticate semantic-release"
          npx semantic-release

      - name: Build and Push Docker Image (make dist)
        env:
          CR_PAT: ${{ secrets.PAT_GITHUB }}
        run: make dist
